### ISSUE TITLE
regex issue

### ISSUE THREAD

**Issue by oleksapershyi** [artisangang/node-input-validator#12]
Hi guys! 
I have some issue with regex validation.
Here is my regex expression:

`let validator = new v(obj, {
	"day": "string|maxLength:9",
	"from": "regex:[/^[0-23]{2}:[0-59]{2}$/g]",
	"to": "regex:[/^[0-23]{2}:[0-59]{2}$/g]"
});`

I found out that validator can work only with the first part of regex expression up to the colon.
This issue was detected by console.log(field, value, pattren)

`module.exports = async function regex(field, value, pattren) {
    console.log(field, value, pattren);
    var regexp = new RegExp(pattren);
    if (!regexp.test(value)) { return false; }
    return true;
}`
... in /node-input-validator/src/rules/regex.js

Here is the output:

{ day: 'Thursday', from: '09:00', to: '10:30' }

from 09:00 [/^[0-23]{2} 
to 10:30 [/^[0-23]{2}
true

As you can see validation works up to the colon and the second part of the regex expression is missed.

P.S. Different regex was tested. It brakes on colons.
P.P.S. Please update documentation in regex section. Specify that the regular expression should be wrapped in square brackets for correct work.

**Comment by artisangang** [comment]
Thanks for pointing this out, regular expression breaks on using colons (:) or pipe delimiters. I forgot this to mention in docs (Added in next release).   I m already working on this issue. Plan is to use array of rules instead of string.


https://github.com/artisangang/node-input-validator/blob/master/test/arrayOfRules.js
